# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[merge]
automerge_label = "automerge"
require_automerge_label = true
method = "merge"
delete_branch_on_merge = true
notify_on_conflict = true

[merge.message]
title = "pull_request_title"
