# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[merge]
automerge_label = "automerge"
require_automerge_label = true
method = "squash"

[merge.message]
title = "github_default"
