name: CheckBranchVersion
 
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:    

jobs:
  Check-Branch-Version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read version from current branch
        run: |
              ls

   
