name: GetCountofApprovers

on:
  #pull_request_review:
  #  branches:
  #    - master
  #  types: [submitted]
    
jobs:
  getcount:
    runs-on: ubuntu-latest

    steps:
    
    - name: List reviews on the pull request
      shell: bash
      run: |
            token=${{ secrets.REPO_TOKEN }}
            base64AuthInfo='$token | base64 -e'
          
            response=$(curl --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            --header 'Authorization: $base64AuthInfo' \
            --header 'Content-Type: application/json')

            echo $response | jq '.[] | select(.state=="APPROVED")'
