# This is a basic workflow to help you get started with Actions

name: GetCountofApprovers

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getcount:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: List reviews on the pull request
      shell: bash
      run: |
            token=${{ secrets.REPO_TOKEN }}
            base64AuthInfo='$token | base64 -e'
          
            response=$(curl --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            --header 'Authorization: $base64AuthInfo' \
            --header 'Content-Type: application/json')

            echo $response | jq '.[] | select(.state=="APPROVED")'
