name: 'Manage PRs to master'
on: 
  pull_request:
    branches: 
      - master
   
jobs:
  add-reviewiers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.REPO_TOKEN }}"
          configuration-path: ".github/PR-Reviewers.yml"

  add-automerge-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.REPO_TOKEN }}"
          configuration-path: ".github/labeler.yml"
          
          
