name: MergeMasterToRelease

on:
  repository_dispatch:
    types: MergeMasterToRelease
  workflow_dispatch:

jobs:
  MergeMasterToRelease:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Merge to release branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
  
      - name: Send message on Slack in case of success
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#general'
          text: 'Merge from master to release branch performed successfully.'
        

      - name: Send message on Slack in case of failure
        if: failure()
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#general'
          text: 'The merge from master to release branch was not successful. Please review.'
          color: 'danger'      
