name: 'Get Jira Status'
on:
  #repository_dispatch:
  #  types: MergeMasterToRelease
  #workflow_dispatch:
  pull_request:
    branches: 
      - master
 
jobs:
  read-jira-status:
    runs-on: ubuntu-latest
    
    steps:
     - name: Read Jira Issue Status
       id: retrieveJiraStatus
       run: |
             nar=$(curl --request GET \
                  --url 'https://naregkar.atlassian.net/rest/api/3/issue/DT-6/' \
                  --user 'nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87' \
                  --header 'Accept: application/json' | jq '.fields.status.name');                   
             #echo $nar
             echo "jira_status=$nar" >> $GITHUB_ENV
     - name: Display Status
       run: |
             echo "${{ env.jira_status }}"
    
     - name: Get Jira Issue ID
       run: |
              echo "{{ github.event.pull_request.title }}"
             
