name: triggerUponPRCreation

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    types: CheckJira
    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: echo This is executed upon PR Creation
        
      - name: Get Jira Issue ID
        run: |
            echo "$GITHUB_PR_TITLE"
            JiraIdUnparsed=$GITHUB_PR_TITLE
            JiraId=${JiraIdUnparsed%]*}
            JiraId=${JiraId:1}
            echo "jira_id=$JiraId" >> $GITHUB_ENV
    
      - name: Read Jira Issue Status
        id: retrieveJiraStatus
        run: |
              restApiGET=$(curl --request GET \
                    --url 'https://naregkar.atlassian.net/rest/api/3/issue/${{ env.jira_id }}/' \
                    --user 'nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87' \
                    --header 'Accept: application/json' | jq '.fields.status.name');                   
               #echo $restApiGET
               echo "jiraIssue_status=$restApiGET" >> $GITHUB_ENV

      - name: Display Status
        run: |
             echo ${{ env.jiraIssue_status }}
             
      - name: Assess the Status / To Do
        run: |
              returnedStatus=${{ env.jiraIssue_status }}
              echo 'returned status is: ' $returnedStatus
              if [ "$returnedStatus" = "Done" ]; then
                echo "Finished.. Success"
              else
                echo "Not finished"
                exit 1
              fi   
