name: UpdatePRTitle

on:
   pull_request:
    types:
      - edited
    branches: 
      - master
env:
  GITHUB_PR_TITLE: ${{github.event.pull_request.title}}
  GITHUB_BRANCH_NAME: ${GITHUB_REF#refs/heads/}

jobs:
  updatePRTitle:
    runs-on: ubuntu-latest
    
    steps:
      - name: Update PR Title
        run:  |
               echo $GITHUB_PR_TITLE
               echo $GITHUB_BRANCH_NAME
               
               restApiGETWorkflowId=$(curl \
                                       -H "Accept: application/vnd.github.v3+json" \
                                       "https://api.github.com/repos/naregkar/testAutoMerge/actions/runs?event=pull_request&branch=nk-1" | jq '.["workflow_runs"]' | jq '.[] | select(.name=="ValidatePRTitle").id'
               
               echo $restApiGETWorkflowId
