name: UpdatePRTitle

on:
   pull_request:
    types:
      - edited
    branches: 
      - master
env:
  GITHUB_PR_TITLE: ${{github.event.pull_request.title}}

jobs:
  updatePRTitle:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo running on branch ${GITHUB_REF##*/}
        
      
      - name: Update PR Title
        run:  |
               
               
               restApiGETWorkflowId=$(curl \
                                       -H "Accept: application/vnd.github.v3+json" \
                                       "https://api.github.com/repos/naregkar/testAutoMerge/actions/runs?event=pull_request&branch=nk-1" | jq '.["workflow_runs"]' | jq '.[] | select(.name=="ValidatePRTitle").id')
               
               echo $restApiGETWorkflowId
