name: UpdatePRBranchVersion
 
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:    

jobs:
  Update-Branch-Version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
              
      - name: Read version from Jira Issue
        run : |
               restApiGET=$(curl --request GET \
                  --url 'https://naregkar.atlassian.net/rest/api/3/issue/DT-11/' \
                  --user 'nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87' \
                  --header 'Accept: application/json' | jq '.fields.fixVersions[].name');                   
            
               echo "issue_fix_version=$restApiGET" >> $GITHUB_ENV
             

      - name: Write to the version file
        run: |
              cd .github
              > version
              
              $issue_fix_version >> version
              cat version
