name: UpdatePRBranchVersion
 
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
env:
  PR_BRANCH_NAME: ${{ github.head_ref }}
 
jobs:
  Update-Branch-Version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=PR_BRANCH_NAME;]$(echo ${GITHUB_REF##*/})"
  
       
      - name: Read version from Jira Issue
        run : |
               restApiGET=$(curl --request GET \
                  --url 'https://naregkar.atlassian.net/rest/api/3/issue/DT-11/' \
                  --user 'nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87' \
                  --header 'Accept: application/json' | jq '.fields.fixVersions[].name');                   
            
               echo "issue_fix_version=$restApiGET" >> $GITHUB_ENV
             

      - name: Write to the version file
        run: |
              cd .github
              > version
              
              echo 'branch is' "${{ env.PR_Branch_Name }}"
              
              echo "$issue_fix_version" >> version
              cat version
              
              git config --global user.name "naregkar"
              git config --global user.email "naregkar@gmail.com"
              
              #git add version
              #git commit -am "Updating the file version"
              #git push
