name: ValidatePRTitle

on:
  pull_request:
    branches: 
      - master
env:
  GITHUB_PR_TITLE: ${{github.event.pull_request.title}}    

jobs:
  validatePR:
    runs-on: ubuntu-latest
    
    steps:
      - name: Valicate PR Title
        run:  |
                echo 'PR Title is:' $GITHUB_PR_TITLE
                string='My string';

                if [[ $string =~ "[123]" ]]; then
                  echo 'expression exists in there!'
                fi


      
