name: ValidatePRTitle

on:
  pull_request:
    branches: 
      - master
env:
  GITHUB_PR_TITLE: ${{github.event.pull_request.title}}    

jobs:
  validatePR:
    runs-on: ubuntu-latest
    
    steps:
      - name: Valicate PR Title
        run:  |
                echo 'PR Title is:' $GITHUB_PR_TITLE

                File=YOUR_FILENAME  
                if grep -q [1234] "$GITHUB_PR_TITLE"; ##note the space after the string you are searching for
                then
                echo "Hooray!!It's available"
                else
                echo "Oops!!Not available"
                fi
